package com.tcl.onetouch.form;

public class ResourceForm extends BaseForm{
	
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column resource.id
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column resource.name
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column resource.value
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    private String value;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column resource.id
     *
     * @return the value of resource.id
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column resource.id
     *
     * @param id the value for resource.id
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column resource.name
     *
     * @return the value of resource.name
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column resource.name
     *
     * @param name the value for resource.name
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column resource.value
     *
     * @return the value of resource.value
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column resource.value
     *
     * @param value the value for resource.value
     *
     * @abatorgenerated Tue May 18 10:36:04 CST 2010
     */
    public void setValue(String value) {
        this.value = value;
    }
}
