package com.tcl.paypal.domain;

import java.util.Date;

public class Gameresource {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.id
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.name
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.images
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private String images;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.file1
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private String file1;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.file2
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private String file2;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.ua
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private String ua;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.spid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private Integer spid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.sdate
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private Date sdate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.lg
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private String lg;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.kindid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private Integer kindid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.typeid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private Integer typeid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.rel
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private Byte rel;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.orderid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private Integer orderid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.sizeid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private Short sizeid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.price
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private String price;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresource.info
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	private String info;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.id
	 * @return  the value of gameresource.id
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.id
	 * @param id  the value for gameresource.id
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.name
	 * @return  the value of gameresource.name
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.name
	 * @param name  the value for gameresource.name
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.images
	 * @return  the value of gameresource.images
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public String getImages() {
		return images;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.images
	 * @param images  the value for gameresource.images
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setImages(String images) {
		this.images = images;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.file1
	 * @return  the value of gameresource.file1
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public String getFile1() {
		return file1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.file1
	 * @param file1  the value for gameresource.file1
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setFile1(String file1) {
		this.file1 = file1;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.file2
	 * @return  the value of gameresource.file2
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public String getFile2() {
		return file2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.file2
	 * @param file2  the value for gameresource.file2
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setFile2(String file2) {
		this.file2 = file2;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.ua
	 * @return  the value of gameresource.ua
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public String getUa() {
		return ua;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.ua
	 * @param ua  the value for gameresource.ua
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setUa(String ua) {
		this.ua = ua;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.spid
	 * @return  the value of gameresource.spid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public Integer getSpid() {
		return spid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.spid
	 * @param spid  the value for gameresource.spid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setSpid(Integer spid) {
		this.spid = spid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.sdate
	 * @return  the value of gameresource.sdate
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public Date getSdate() {
		return sdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.sdate
	 * @param sdate  the value for gameresource.sdate
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setSdate(Date sdate) {
		this.sdate = sdate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.lg
	 * @return  the value of gameresource.lg
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public String getLg() {
		return lg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.lg
	 * @param lg  the value for gameresource.lg
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setLg(String lg) {
		this.lg = lg;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.kindid
	 * @return  the value of gameresource.kindid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public Integer getKindid() {
		return kindid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.kindid
	 * @param kindid  the value for gameresource.kindid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setKindid(Integer kindid) {
		this.kindid = kindid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.typeid
	 * @return  the value of gameresource.typeid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public Integer getTypeid() {
		return typeid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.typeid
	 * @param typeid  the value for gameresource.typeid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.rel
	 * @return  the value of gameresource.rel
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public Byte getRel() {
		return rel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.rel
	 * @param rel  the value for gameresource.rel
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setRel(Byte rel) {
		this.rel = rel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.orderid
	 * @return  the value of gameresource.orderid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public Integer getOrderid() {
		return orderid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.orderid
	 * @param orderid  the value for gameresource.orderid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setOrderid(Integer orderid) {
		this.orderid = orderid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.sizeid
	 * @return  the value of gameresource.sizeid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public Short getSizeid() {
		return sizeid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.sizeid
	 * @param sizeid  the value for gameresource.sizeid
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setSizeid(Short sizeid) {
		this.sizeid = sizeid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.price
	 * @return  the value of gameresource.price
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.price
	 * @param price  the value for gameresource.price
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column gameresource.info
	 * @return  the value of gameresource.info
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public String getInfo() {
		return info;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column gameresource.info
	 * @param info  the value for gameresource.info
	 * @abatorgenerated  Tue Sep 28 14:17:29 CST 2010
	 */
	public void setInfo(String info) {
		this.info = info;
	}
}