package com.tcl.gamePortal.form;

public class IpinfoForm extends BaseForm{
	
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ipinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ipinfo.ip
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private String ip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ipinfo.proviceId
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer proviceid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ipinfo.country
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer country;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ipinfo.telecomOperators
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer telecomoperators;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column ipinfo.city
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer city;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ipinfo.id
     *
     * @return the value of ipinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ipinfo.id
     *
     * @param id the value for ipinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ipinfo.ip
     *
     * @return the value of ipinfo.ip
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ipinfo.ip
     *
     * @param ip the value for ipinfo.ip
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ipinfo.proviceId
     *
     * @return the value of ipinfo.proviceId
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Integer getProviceid() {
        return proviceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ipinfo.proviceId
     *
     * @param proviceid the value for ipinfo.proviceId
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setProviceid(Integer proviceid) {
        this.proviceid = proviceid;
    }



    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ipinfo.telecomOperators
     *
     * @return the value of ipinfo.telecomOperators
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Integer getTelecomoperators() {
        return telecomoperators;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ipinfo.telecomOperators
     *
     * @param telecomoperators the value for ipinfo.telecomOperators
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setTelecomoperators(Integer telecomoperators) {
        this.telecomoperators = telecomoperators;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column ipinfo.city
     *
     * @return the value of ipinfo.city
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column ipinfo.city
     *
     * @param city the value for ipinfo.city
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setCity(Integer city) {
        this.city = city;
    }

	public Integer getCountry() {
		return country;
	}

	public void setCountry(Integer country) {
		this.country = country;
	}
}
