package com.tcl.wapStatistic.domain;

public class Location {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column location.id
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    private Long id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column location.ip
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    private String ip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column location.country
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    private String country;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column location.city
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    private String city;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column location.operator
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    private String operator;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column location.description
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    private String description;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column location.id
     *
     * @return the value of location.id
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column location.id
     *
     * @param id the value for location.id
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column location.ip
     *
     * @return the value of location.ip
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column location.ip
     *
     * @param ip the value for location.ip
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column location.country
     *
     * @return the value of location.country
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column location.country
     *
     * @param country the value for location.country
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column location.city
     *
     * @return the value of location.city
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column location.city
     *
     * @param city the value for location.city
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column location.operator
     *
     * @return the value of location.operator
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column location.operator
     *
     * @param operator the value for location.operator
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column location.description
     *
     * @return the value of location.description
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column location.description
     *
     * @param description the value for location.description
     *
     * @abatorgenerated Mon Dec 06 09:23:48 CST 2010
     */
    public void setDescription(String description) {
        this.description = description;
    }
}