package com.tcl.onetouch.domain;

import java.util.Date;

public class Ad {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.id
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.name
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.spid
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private Integer spid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.url
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private String url;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.image
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private String image;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.disable
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private Integer disable;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.did
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private String did;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.brief
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private String brief;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column ad.atime
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	private Date atime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.id
	 * @return  the value of ad.id
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.id
	 * @param id  the value for ad.id
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.name
	 * @return  the value of ad.name
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.name
	 * @param name  the value for ad.name
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.spid
	 * @return  the value of ad.spid
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public Integer getSpid() {
		return spid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.spid
	 * @param spid  the value for ad.spid
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setSpid(Integer spid) {
		this.spid = spid;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.url
	 * @return  the value of ad.url
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.url
	 * @param url  the value for ad.url
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.image
	 * @return  the value of ad.image
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public String getImage() {
		return image;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.image
	 * @param image  the value for ad.image
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setImage(String image) {
		this.image = image;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.disable
	 * @return  the value of ad.disable
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public Integer getDisable() {
		return disable;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.disable
	 * @param disable  the value for ad.disable
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setDisable(Integer disable) {
		this.disable = disable;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.did
	 * @return  the value of ad.did
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public String getDid() {
		return did;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.did
	 * @param did  the value for ad.did
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setDid(String did) {
		this.did = did;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.brief
	 * @return  the value of ad.brief
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.brief
	 * @param brief  the value for ad.brief
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column ad.atime
	 * @return  the value of ad.atime
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public Date getAtime() {
		return atime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column ad.atime
	 * @param atime  the value for ad.atime
	 * @abatorgenerated  Fri May 20 16:18:35 CST 2011
	 */
	public void setAtime(Date atime) {
		this.atime = atime;
	}
	
	private String didName;

	public String getDidName() {
		return didName;
	}

	public void setDidName(String didName) {
		this.didName = didName;
	}
	
	private String spName;

	public String getSpName() {
		return spName;
	}

	public void setSpName(String spName) {
		this.spName = spName;
	}

}