package com.tcl.onetouch.form;

public class GameLanguageForm extends BaseForm{
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game_language.id
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game_language.game_id
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    private Integer gameId;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game_language.language
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    private Integer language;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game_language.name
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game_language.detailInfo
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    private String detailinfo;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game_language.brief
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    private String brief;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game_language.imageName
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    private String imagename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column game_language.icon
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    private String icon;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game_language.id
     *
     * @return the value of game_language.id
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game_language.id
     *
     * @param id the value for game_language.id
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game_language.game_id
     *
     * @return the value of game_language.game_id
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game_language.game_id
     *
     * @param gameId the value for game_language.game_id
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game_language.language
     *
     * @return the value of game_language.language
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public Integer getLanguage() {
        return language;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game_language.language
     *
     * @param language the value for game_language.language
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public void setLanguage(Integer language) {
        this.language = language;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game_language.name
     *
     * @return the value of game_language.name
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game_language.name
     *
     * @param name the value for game_language.name
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game_language.detailInfo
     *
     * @return the value of game_language.detailInfo
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public String getDetailinfo() {
        return detailinfo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game_language.detailInfo
     *
     * @param detailinfo the value for game_language.detailInfo
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public void setDetailinfo(String detailinfo) {
        this.detailinfo = detailinfo;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game_language.brief
     *
     * @return the value of game_language.brief
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game_language.brief
     *
     * @param brief the value for game_language.brief
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public void setBrief(String brief) {
        this.brief = brief;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game_language.imageName
     *
     * @return the value of game_language.imageName
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public String getImagename() {
        return imagename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game_language.imageName
     *
     * @param imagename the value for game_language.imageName
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public void setImagename(String imagename) {
        this.imagename = imagename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column game_language.icon
     *
     * @return the value of game_language.icon
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column game_language.icon
     *
     * @param icon the value for game_language.icon
     *
     * @abatorgenerated Mon Oct 17 15:04:22 CST 2011
     */
    public void setIcon(String icon) {
        this.icon = icon;
    }
}