package com.tcl.onetouch.form;

public class RoleForm extends BaseForm{
	
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column role.id
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column role.name
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column role.description
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	private String description;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column role.resources
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	private String resources;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column role.id
	 * @return  the value of role.id
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column role.id
	 * @param id  the value for role.id
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column role.name
	 * @return  the value of role.name
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column role.name
	 * @param name  the value for role.name
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column role.description
	 * @return  the value of role.description
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column role.description
	 * @param description  the value for role.description
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column role.resources
	 * @return  the value of role.resources
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	public String getResources() {
		return resources;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column role.resources
	 * @param resources  the value for role.resources
	 * @abatorgenerated  Wed May 19 09:21:05 CST 2010
	 */
	public void setResources(String resources) {
		this.resources = resources;
	}
}
