package com.tcl.onetouch.form;

import java.util.Date;

public class UserMessageForm extends BaseForm{

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_message.id
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_message.inei
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	private String inei;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_message.sms
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	private String sms;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column user_message.save_time
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	private Date saveTime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_message.id
	 * @return  the value of user_message.id
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_message.id
	 * @param id  the value for user_message.id
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_message.inei
	 * @return  the value of user_message.inei
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	public String getInei() {
		return inei;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_message.inei
	 * @param inei  the value for user_message.inei
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	public void setInei(String inei) {
		this.inei = inei;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_message.sms
	 * @return  the value of user_message.sms
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	public String getSms() {
		return sms;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_message.sms
	 * @param sms  the value for user_message.sms
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	public void setSms(String sms) {
		this.sms = sms;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column user_message.save_time
	 * @return  the value of user_message.save_time
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	public Date getSaveTime() {
		return saveTime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column user_message.save_time
	 * @param saveTime  the value for user_message.save_time
	 * @abatorgenerated  Wed Jun 01 10:17:49 CST 2011
	 */
	public void setSaveTime(Date saveTime) {
		this.saveTime = saveTime;
	}
}