package com.tcl.onetouch.form;

import java.util.Date;

public class CustomerForm extends BaseForm{
	
	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer.userName
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private String username;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer.password
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer.email
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Object email;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer.mobile
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private String mobile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column customer.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Date ctime;
    
    private Integer point;
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer.id
     *
     * @return the value of customer.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer.id
     *
     * @param id the value for customer.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer.userName
     *
     * @return the value of customer.userName
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer.userName
     *
     * @param username the value for customer.userName
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer.password
     *
     * @return the value of customer.password
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer.password
     *
     * @param password the value for customer.password
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer.email
     *
     * @return the value of customer.email
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Object getEmail() {
        return email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer.email
     *
     * @param email the value for customer.email
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setEmail(Object email) {
        this.email = email;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer.mobile
     *
     * @return the value of customer.mobile
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer.mobile
     *
     * @param mobile the value for customer.mobile
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column customer.ctime
     *
     * @return the value of customer.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column customer.ctime
     *
     * @param ctime the value for customer.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public Integer getPoint() {
		return point;
	}

	public void setPoint(Integer point) {
		this.point = point;
	}

}
