package com.tcl.onetouch.form;

import java.util.Date;

import org.apache.struts.upload.FormFile;

public class GameresouceForm extends BaseForm{
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.id
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.gameId
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private Integer gameid;
	
	private Integer countryid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.provinceId
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private Integer provinceid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.did
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private String did;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.startTime
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private Date starttime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.jarFile
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private String jarfile;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.jadFile
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private String jadfile;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.path
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private String path;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.priority
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private Integer priority;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.type
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private Integer typeid;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.disable
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private Integer disable;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column gameresouce.fileName
	 * @abatorgenerated  Tue Aug 24 16:29:37 CST 2010
	 */
	private String filename;
	
    private Integer resourcetype;
    
    private String url;
    
	private String remark;
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.id
     *
     * @return the value of gameresouce.id
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.id
     *
     * @param id the value for gameresouce.id
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.gameId
     *
     * @return the value of gameresouce.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.gameId
     *
     * @param gameid the value for gameresouce.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }
    
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.countryId
     *
     * @return the value of gameresouce.countryId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.countryId
     *
     * @param countryid the value for gameresouce.countryId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }
    
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.provinceId
     *
     * @return the value of gameresouce.provinceId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.provinceId
     *
     * @param provinceid the value for gameresouce.provinceId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.did
     *
     * @return the value of gameresouce.did
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public String getDid() {
        return did;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.did
     *
     * @param did the value for gameresouce.did
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.startTime
     *
     * @return the value of gameresouce.startTime
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.startTime
     *
     * @param starttime the value for gameresouce.startTime
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

  

   

    public String getJarfile() {
		return jarfile;
	}

	public void setJarfile(String jarfile) {
		this.jarfile = jarfile;
	}

	public String getJadfile() {
		return jadfile;
	}

	public void setJadfile(String jadfile) {
		this.jadfile = jadfile;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.path
     *
     * @return the value of gameresouce.path
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.path
     *
     * @param path the value for gameresouce.path
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.priority
     *
     * @return the value of gameresouce.priority
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.priority
     *
     * @param priority the value for gameresouce.priority
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    public Integer getTypeid() {
		return typeid;
	}

	public void setTypeid(Integer typeid) {
		this.typeid = typeid;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.disable
     *
     * @return the value of gameresouce.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getDisable() {
        return disable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.disable
     *
     * @param disable the value for gameresouce.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setDisable(Integer disable) {
        this.disable = disable;
    }
    
    
    private Long price;
    
    
    private String gameName;

	public String getGameName() {
		return gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}
	
	  private String provinceName;

		public String getProvinceName() {
			return provinceName;
		}

		public void setProvinceName(String provinceName) {
			this.provinceName = provinceName;
		}

		public Long getPrice() {
			return price;
		}

		public void setPrice(Long price) {
			this.price = price;
		}

		public String getFilename() {
			return filename;
		}

		public void setFilename(String filename) {
			this.filename = filename;
		}
		
		private FormFile fileOne;
		
		private FormFile fileTwo;
		
		public FormFile getFileOne() {
			return fileOne;
		}

		public void setFileOne(FormFile fileOne) {
			this.fileOne = fileOne;
		}

		public FormFile getFileTwo() {
			return fileTwo;
		}

		public void setFileTwo(FormFile fileTwo) {
			this.fileTwo = fileTwo;
		}

		public String getRemark() {
			return remark;
		}

		public void setRemark(String remark) {
			this.remark = remark;
		}

		public Integer getResourcetype() {
			return resourcetype;
		}

		public void setResourcetype(Integer resourcetype) {
			this.resourcetype = resourcetype;
		}

		public String getUrl() {
			return url;
		}

		public void setUrl(String url) {
			this.url = url;
		}
		
}