package com.tcl.onetouch.domain;

import java.util.Date;

public class Gameresouce {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.id
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.gameId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer gameid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.countryId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer countryid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.provinceId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer provinceid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.did
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String did;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.startTime
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Date starttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.jarFile
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String jarfile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.jadFile
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String jadfile;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.path
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String path;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.priority
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer priority;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.typeId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer typeid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.disable
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer disable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.fileName
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String filename;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.price
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Long price;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.url
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String url;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.resourceType
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer resourcetype;
    
    private String remark;
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.id
     *
     * @return the value of gameresouce.id
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.id
     *
     * @param id the value for gameresouce.id
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.gameId
     *
     * @return the value of gameresouce.gameId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.gameId
     *
     * @param gameid the value for gameresouce.gameId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.countryId
     *
     * @return the value of gameresouce.countryId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getCountryid() {
        return countryid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.countryId
     *
     * @param countryid the value for gameresouce.countryId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setCountryid(Integer countryid) {
        this.countryid = countryid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.provinceId
     *
     * @return the value of gameresouce.provinceId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.provinceId
     *
     * @param provinceid the value for gameresouce.provinceId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.did
     *
     * @return the value of gameresouce.did
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getDid() {
        return did;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.did
     *
     * @param did the value for gameresouce.did
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.startTime
     *
     * @return the value of gameresouce.startTime
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.startTime
     *
     * @param starttime the value for gameresouce.startTime
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.jarFile
     *
     * @return the value of gameresouce.jarFile
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getJarfile() {
        return jarfile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.jarFile
     *
     * @param jarfile the value for gameresouce.jarFile
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setJarfile(String jarfile) {
        this.jarfile = jarfile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.jadFile
     *
     * @return the value of gameresouce.jadFile
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getJadfile() {
        return jadfile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.jadFile
     *
     * @param jadfile the value for gameresouce.jadFile
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setJadfile(String jadfile) {
        this.jadfile = jadfile;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.path
     *
     * @return the value of gameresouce.path
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.path
     *
     * @param path the value for gameresouce.path
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.priority
     *
     * @return the value of gameresouce.priority
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.priority
     *
     * @param priority the value for gameresouce.priority
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.typeId
     *
     * @return the value of gameresouce.typeId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.typeId
     *
     * @param typeid the value for gameresouce.typeId
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setTypeid(Integer typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.disable
     *
     * @return the value of gameresouce.disable
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getDisable() {
        return disable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.disable
     *
     * @param disable the value for gameresouce.disable
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setDisable(Integer disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.fileName
     *
     * @return the value of gameresouce.fileName
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.fileName
     *
     * @param filename the value for gameresouce.fileName
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setFilename(String filename) {
        this.filename = filename;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.price
     *
     * @return the value of gameresouce.price
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.price
     *
     * @param price the value for gameresouce.price
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.url
     *
     * @return the value of gameresouce.url
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.url
     *
     * @param url the value for gameresouce.url
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.resourceType
     *
     * @return the value of gameresouce.resourceType
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getResourcetype() {
        return resourcetype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.resourceType
     *
     * @param resourcetype the value for gameresouce.resourceType
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setResourcetype(Integer resourcetype) {
        this.resourcetype = resourcetype;
    }
    
	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}
	
    private String gameName;

	public String getGameName() {
		return gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}
	
	private String provinceName;

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}

	private String didName;

	public String getDidName() {
		return didName;
	}

	public void setDidName(String didName) {
		this.didName = didName;
	}
		   
	private String typeName;


	public String getTypeName() {
		return typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}
			
}