package com.tcl.onetouch.domain;

import java.util.Date;

public class Images {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column images.id
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column images.name
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column images.size
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String size;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column images.remark
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column images.saveTime
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Date savetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column images.type
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    private Integer type;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column images.id
     *
     * @return the value of images.id
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column images.id
     *
     * @param id the value for images.id
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column images.name
     *
     * @return the value of images.name
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column images.name
     *
     * @param name the value for images.name
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column images.size
     *
     * @return the value of images.size
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column images.size
     *
     * @param size the value for images.size
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column images.remark
     *
     * @return the value of images.remark
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column images.remark
     *
     * @param remark the value for images.remark
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column images.saveTime
     *
     * @return the value of images.saveTime
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Date getSavetime() {
        return savetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column images.saveTime
     *
     * @param savetime the value for images.saveTime
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setSavetime(Date savetime) {
        this.savetime = savetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column images.type
     *
     * @return the value of images.type
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column images.type
     *
     * @param type the value for images.type
     *
     * @abatorgenerated Tue Sep 13 10:56:14 CST 2011
     */
    public void setType(Integer type) {
        this.type = type;
    }
}