package com.tcl.onetouch.domain;

public class MobileGame {
		public static String CACHE_MOBILEGAME = "mobileGameCache";
		/**
		 * This field was generated by Abator for iBATIS. This field corresponds to the database column mobile_game.id
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		private Integer id;
		/**
		 * This field was generated by Abator for iBATIS. This field corresponds to the database column mobile_game.did
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		private String did;
		/**
		 * This field was generated by Abator for iBATIS. This field corresponds to the database column mobile_game.game_id
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		private Integer gameId;
		/**
		 * This field was generated by Abator for iBATIS. This field corresponds to the database column mobile_game.priority
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		private Integer priority;

		/**
		 * This method was generated by Abator for iBATIS. This method returns the value of the database column mobile_game.id
		 * @return  the value of mobile_game.id
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		public Integer getId() {
			return id;
		}

		/**
		 * This method was generated by Abator for iBATIS. This method sets the value of the database column mobile_game.id
		 * @param id  the value for mobile_game.id
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		public void setId(Integer id) {
			this.id = id;
		}

		/**
		 * This method was generated by Abator for iBATIS. This method returns the value of the database column mobile_game.did
		 * @return  the value of mobile_game.did
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		public String getDid() {
			return did;
		}

		/**
		 * This method was generated by Abator for iBATIS. This method sets the value of the database column mobile_game.did
		 * @param did  the value for mobile_game.did
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		public void setDid(String did) {
			this.did = did;
		}

		/**
		 * This method was generated by Abator for iBATIS. This method returns the value of the database column mobile_game.game_id
		 * @return  the value of mobile_game.game_id
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		public Integer getGameId() {
			return gameId;
		}

		/**
		 * This method was generated by Abator for iBATIS. This method sets the value of the database column mobile_game.game_id
		 * @param gameId  the value for mobile_game.game_id
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		public void setGameId(Integer gameId) {
			this.gameId = gameId;
		}

		/**
		 * This method was generated by Abator for iBATIS. This method returns the value of the database column mobile_game.priority
		 * @return  the value of mobile_game.priority
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		public Integer getPriority() {
			return priority;
		}

		/**
		 * This method was generated by Abator for iBATIS. This method sets the value of the database column mobile_game.priority
		 * @param priority  the value for mobile_game.priority
		 * @abatorgenerated  Wed Nov 23 18:02:14 CST 2011
		 */
		public void setPriority(Integer priority) {
			this.priority = priority;
		}

		
	}
