package com.tcl.onetouch.domain;

import java.util.Date;

public class Musics {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column musics.id
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column musics.name
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column musics.remark
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    private String remark;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column musics.saveTime
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    private Date savetime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column musics.type
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    private Integer type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column musics.format
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    private Integer format;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column musics.id
     *
     * @return the value of musics.id
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column musics.id
     *
     * @param id the value for musics.id
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column musics.name
     *
     * @return the value of musics.name
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column musics.name
     *
     * @param name the value for musics.name
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column musics.remark
     *
     * @return the value of musics.remark
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column musics.remark
     *
     * @param remark the value for musics.remark
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column musics.saveTime
     *
     * @return the value of musics.saveTime
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public Date getSavetime() {
        return savetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column musics.saveTime
     *
     * @param savetime the value for musics.saveTime
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public void setSavetime(Date savetime) {
        this.savetime = savetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column musics.type
     *
     * @return the value of musics.type
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column musics.type
     *
     * @param type the value for musics.type
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column musics.format
     *
     * @return the value of musics.format
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public Integer getFormat() {
        return format;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column musics.format
     *
     * @param format the value for musics.format
     *
     * @abatorgenerated Tue Sep 13 10:56:16 CST 2011
     */
    public void setFormat(Integer format) {
        this.format = format;
    }
}