package com.tcl.onetouch.domain;

import java.io.Serializable;

public class City {
    public static final Serializable CACHE_CITY = "cityCache";

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column city.id
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column city.cityName
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private String cityname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column city.provinceId
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private Integer provinceid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column city.remarker
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private String remarker;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column city.cityCode
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private String citycode;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column city.id
     *
     * @return the value of city.id
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column city.id
     *
     * @param id the value for city.id
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column city.cityName
     *
     * @return the value of city.cityName
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public String getCityname() {
        return cityname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column city.cityName
     *
     * @param cityname the value for city.cityName
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setCityname(String cityname) {
        this.cityname = cityname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column city.provinceId
     *
     * @return the value of city.provinceId
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column city.provinceId
     *
     * @param provinceid the value for city.provinceId
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column city.remarker
     *
     * @return the value of city.remarker
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public String getRemarker() {
        return remarker;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column city.remarker
     *
     * @param remarker the value for city.remarker
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setRemarker(String remarker) {
        this.remarker = remarker;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column city.cityCode
     *
     * @return the value of city.cityCode
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public String getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column city.cityCode
     *
     * @param citycode the value for city.cityCode
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setCitycode(String citycode) {
        this.citycode = citycode;
    }
    
    private String countryName;

	public String getCountryName() {
		return countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}
    
    private String provinceName;

	public String getProvinceName() {
		return provinceName;
	}

	public void setProvinceName(String provinceName) {
		this.provinceName = provinceName;
	}
	
	private Integer countryId;

	public Integer getCountryId() {
		return countryId;
	}

	public void setCountryId(Integer countryId) {
		this.countryId = countryId;
	}

	

}