package com.tcl.paypal.form;

import java.util.Date;

public class GoodsForm extends BaseForm{
	

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column goods.id
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column goods.name
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	private String name;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column goods.price
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	private String price;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column goods.jarName
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	private String jarname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column goods.jadName
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	private String jadname;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column goods.addTime
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	private Date addtime;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column goods.id
	 * @return  the value of goods.id
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column goods.id
	 * @param id  the value for goods.id
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column goods.name
	 * @return  the value of goods.name
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column goods.name
	 * @param name  the value for goods.name
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column goods.price
	 * @return  the value of goods.price
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public String getPrice() {
		return price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column goods.price
	 * @param price  the value for goods.price
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public void setPrice(String price) {
		this.price = price;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column goods.jarName
	 * @return  the value of goods.jarName
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public String getJarname() {
		return jarname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column goods.jarName
	 * @param jarname  the value for goods.jarName
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public void setJarname(String jarname) {
		this.jarname = jarname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column goods.jadName
	 * @return  the value of goods.jadName
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public String getJadname() {
		return jadname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column goods.jadName
	 * @param jadname  the value for goods.jadName
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public void setJadname(String jadname) {
		this.jadname = jadname;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column goods.addTime
	 * @return  the value of goods.addTime
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column goods.addTime
	 * @param addtime  the value for goods.addTime
	 * @abatorgenerated  Thu Sep 23 13:58:20 CST 2010
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

}
