package com.tcl.gamePortal.domain;

import java.io.Serializable;

public class Country {
    public static final Serializable CACHE_COUNTRY = "countryCache";

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column country.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column country.shorterForm
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private String shorterform;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column country.name
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private String name;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column country.id
     *
     * @return the value of country.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column country.id
     *
     * @param id the value for country.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column country.shorterForm
     *
     * @return the value of country.shorterForm
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public String getShorterform() {
        return shorterform;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column country.shorterForm
     *
     * @param shorterform the value for country.shorterForm
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setShorterform(String shorterform) {
        this.shorterform = shorterform;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column country.name
     *
     * @return the value of country.name
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column country.name
     *
     * @param name the value for country.name
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setName(String name) {
        this.name = name;
    }
}