package com.tcl.gamePortal.domain;

import java.util.Date;
/**
 * 游戏资源信息
 * @author kun.shen
 *
 */
public class Gameresouce {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.id
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer gameid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.provinceId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer provinceid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.did
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private String did;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.startTime
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Date starttime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.resource
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private String resource;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.resource2
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private String resource2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.path
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private String path;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.priority
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer priority;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.type
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column gameresouce.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer disable;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.id
     *
     * @return the value of gameresouce.id
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.id
     *
     * @param id the value for gameresouce.id
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.gameId
     *
     * @return the value of gameresouce.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.gameId
     *
     * @param gameid the value for gameresouce.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.provinceId
     *
     * @return the value of gameresouce.provinceId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getProvinceid() {
        return provinceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.provinceId
     *
     * @param provinceid the value for gameresouce.provinceId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setProvinceid(Integer provinceid) {
        this.provinceid = provinceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.did
     *
     * @return the value of gameresouce.did
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public String getDid() {
        return did;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.did
     *
     * @param did the value for gameresouce.did
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.startTime
     *
     * @return the value of gameresouce.startTime
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.startTime
     *
     * @param starttime the value for gameresouce.startTime
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.resource
     *
     * @return the value of gameresouce.resource
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public String getResource() {
        return resource;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.resource
     *
     * @param resource the value for gameresouce.resource
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setResource(String resource) {
        this.resource = resource;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.resource2
     *
     * @return the value of gameresouce.resource2
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public String getResource2() {
        return resource2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.resource2
     *
     * @param resource2 the value for gameresouce.resource2
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setResource2(String resource2) {
        this.resource2 = resource2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.path
     *
     * @return the value of gameresouce.path
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public String getPath() {
        return path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.path
     *
     * @param path the value for gameresouce.path
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.priority
     *
     * @return the value of gameresouce.priority
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getPriority() {
        return priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.priority
     *
     * @param priority the value for gameresouce.priority
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.type
     *
     * @return the value of gameresouce.type
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.type
     *
     * @param type the value for gameresouce.type
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column gameresouce.disable
     *
     * @return the value of gameresouce.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getDisable() {
        return disable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column gameresouce.disable
     *
     * @param disable the value for gameresouce.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setDisable(Integer disable) {
        this.disable = disable;
    }
    
    private Long price;
    
    
    private String gameName;

	public String getGameName() {
		return gameName;
	}

	public void setGameName(String gameName) {
		this.gameName = gameName;
	}
	
	  private String provinceName;

		public String getProvinceName() {
			return provinceName;
		}

		public void setProvinceName(String provinceName) {
			this.provinceName = provinceName;
		}

		public Long getPrice() {
			return price;
		}

		public void setPrice(Long price) {
			this.price = price;
		}
}