package com.tcl.gamePortal.domain;

import java.util.Date;
/**
 * 访问信息
 * @author kun.shen
 *
 */
public class Visiteinfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column visiteinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column visiteinfo.ip
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    private String ip;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column visiteinfo.telephone
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    private String telephone;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column visiteinfo.ua
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    private String ua;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column visiteinfo.titleId
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    private Integer titleid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column visiteinfo.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    private Integer gameid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column visiteinfo.location
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    private Integer location;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column visiteinfo.vtime
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    private Date vtime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column visiteinfo.id
     *
     * @return the value of visiteinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column visiteinfo.id
     *
     * @param id the value for visiteinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column visiteinfo.ip
     *
     * @return the value of visiteinfo.ip
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column visiteinfo.ip
     *
     * @param ip the value for visiteinfo.ip
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column visiteinfo.telephone
     *
     * @return the value of visiteinfo.telephone
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column visiteinfo.telephone
     *
     * @param telephone the value for visiteinfo.telephone
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column visiteinfo.ua
     *
     * @return the value of visiteinfo.ua
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public String getUa() {
        return ua;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column visiteinfo.ua
     *
     * @param ua the value for visiteinfo.ua
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public void setUa(String ua) {
        this.ua = ua;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column visiteinfo.titleId
     *
     * @return the value of visiteinfo.titleId
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public Integer getTitleid() {
        return titleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column visiteinfo.titleId
     *
     * @param titleid the value for visiteinfo.titleId
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public void setTitleid(Integer titleid) {
        this.titleid = titleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column visiteinfo.gameId
     *
     * @return the value of visiteinfo.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column visiteinfo.gameId
     *
     * @param gameid the value for visiteinfo.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column visiteinfo.location
     *
     * @return the value of visiteinfo.location
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public Integer getLocation() {
        return location;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column visiteinfo.location
     *
     * @param location the value for visiteinfo.location
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public void setLocation(Integer location) {
        this.location = location;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column visiteinfo.vtime
     *
     * @return the value of visiteinfo.vtime
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public Date getVtime() {
        return vtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column visiteinfo.vtime
     *
     * @param vtime the value for visiteinfo.vtime
     *
     * @abatorgenerated Wed Jul 28 14:13:05 CST 2010
     */
    public void setVtime(Date vtime) {
        this.vtime = vtime;
    }
}