package com.tcl.portal.domain;

import java.util.Date;

public class Downloadinfo {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column downloadinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column downloadinfo.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer gameid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column downloadinfo.customerId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer customerid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column downloadinfo.ipId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer ipid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column downloadinfo.ua
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
	private String did;
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column downloadinfo.titleId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer titleid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column downloadinfo.location
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Integer location;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column downloadinfo.dtime
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    private Date dtime;
    
    private String telephone;
    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column downloadinfo.id
     *
     * @return the value of downloadinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column downloadinfo.id
     *
     * @param id the value for downloadinfo.id
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column downloadinfo.gameId
     *
     * @return the value of downloadinfo.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column downloadinfo.gameId
     *
     * @param gameid the value for downloadinfo.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column downloadinfo.customerId
     *
     * @return the value of downloadinfo.customerId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column downloadinfo.customerId
     *
     * @param customerid the value for downloadinfo.customerId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setCustomerid(Integer customerid) {
        this.customerid = customerid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column downloadinfo.ipId
     *
     * @return the value of downloadinfo.ipId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getIpid() {
        return ipid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column downloadinfo.ipId
     *
     * @param ipid the value for downloadinfo.ipId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setIpid(Integer ipid) {
        this.ipid = ipid;
    }


    public String getDid() {
		return did;
	}

	public void setDid(String did) {
		this.did = did;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column downloadinfo.titleId
     *
     * @return the value of downloadinfo.titleId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getTitleid() {
        return titleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column downloadinfo.titleId
     *
     * @param titleid the value for downloadinfo.titleId
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setTitleid(Integer titleid) {
        this.titleid = titleid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column downloadinfo.location
     *
     * @return the value of downloadinfo.location
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Integer getLocation() {
        return location;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column downloadinfo.location
     *
     * @param location the value for downloadinfo.location
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setLocation(Integer location) {
        this.location = location;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column downloadinfo.dtime
     *
     * @return the value of downloadinfo.dtime
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public Date getDtime() {
        return dtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column downloadinfo.dtime
     *
     * @param dtime the value for downloadinfo.dtime
     *
     * @abatorgenerated Wed Jul 28 14:13:02 CST 2010
     */
    public void setDtime(Date dtime) {
        this.dtime = dtime;
    }

	public String getTelephone() {
		return telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}
	
	  private String didName;

		public String getDidName() {
			return didName;
		}

		public void setDidName(String didName) {
			this.didName = didName;
		}
	
		private String gameName;

		public String getGameName() {
			return gameName;
		}

		public void setGameName(String gameName) {
			this.gameName = gameName;
		}
}