package com.tcl.portal.domain;

public class Locationpage {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column locationpage.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column locationpage.localName
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private String localname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column locationpage.local
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private String local;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column locationpage.id
     *
     * @return the value of locationpage.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column locationpage.id
     *
     * @param id the value for locationpage.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column locationpage.localName
     *
     * @return the value of locationpage.localName
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public String getLocalname() {
        return localname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column locationpage.localName
     *
     * @param localname the value for locationpage.localName
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setLocalname(String localname) {
        this.localname = localname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column locationpage.local
     *
     * @return the value of locationpage.local
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public String getLocal() {
        return local;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column locationpage.local
     *
     * @param local the value for locationpage.local
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setLocal(String local) {
        this.local = local;
    }
}