package com.tcl.portal.domain;

import java.util.Date;

public class Logs {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logs.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logs.userId
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer userid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logs.doSomthing
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private String dosomthing;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column logs.ltime
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Date ltime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logs.id
     *
     * @return the value of logs.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logs.id
     *
     * @param id the value for logs.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logs.userId
     *
     * @return the value of logs.userId
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logs.userId
     *
     * @param userid the value for logs.userId
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logs.doSomthing
     *
     * @return the value of logs.doSomthing
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public String getDosomthing() {
        return dosomthing;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logs.doSomthing
     *
     * @param dosomthing the value for logs.doSomthing
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setDosomthing(String dosomthing) {
        this.dosomthing = dosomthing;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column logs.ltime
     *
     * @return the value of logs.ltime
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Date getLtime() {
        return ltime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column logs.ltime
     *
     * @param ltime the value for logs.ltime
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setLtime(Date ltime) {
        this.ltime = ltime;
    }
}