package com.tcl.portal.domain;

import java.util.Date;

public class Mobileinfo {

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.did
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private String did;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.phoneType
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private String phonetype;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.screen
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private String screen;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.ua
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private String ua;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.wap
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private Integer wap;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.pageid
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private Integer pageid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.type
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private Integer type;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.javaParameter
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private String javaparameter;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.reserve1
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private String reserve1;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.reserve2
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private String reserve2;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.mtime
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private Date mtime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column mobileinfo.remark
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    private String remark;


    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.did
     *
     * @return the value of mobileinfo.did
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public String getDid() {
        return did;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.did
     *
     * @param did the value for mobileinfo.did
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.phoneType
     *
     * @return the value of mobileinfo.phoneType
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public String getPhonetype() {
        return phonetype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.phoneType
     *
     * @param phonetype the value for mobileinfo.phoneType
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setPhonetype(String phonetype) {
        this.phonetype = phonetype;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.screen
     *
     * @return the value of mobileinfo.screen
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public String getScreen() {
        return screen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.screen
     *
     * @param screen the value for mobileinfo.screen
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setScreen(String screen) {
        this.screen = screen;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.ua
     *
     * @return the value of mobileinfo.ua
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public String getUa() {
        return ua;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.ua
     *
     * @param ua the value for mobileinfo.ua
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setUa(String ua) {
        this.ua = ua;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.wap
     *
     * @return the value of mobileinfo.wap
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public Integer getWap() {
        return wap;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.wap
     *
     * @param wap the value for mobileinfo.wap
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setWap(Integer wap) {
        this.wap = wap;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.pageid
     *
     * @return the value of mobileinfo.pageid
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public Integer getPageid() {
        return pageid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.pageid
     *
     * @param pageid the value for mobileinfo.pageid
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setPageid(Integer pageid) {
        this.pageid = pageid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.type
     *
     * @return the value of mobileinfo.type
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.type
     *
     * @param type the value for mobileinfo.type
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.javaParameter
     *
     * @return the value of mobileinfo.javaParameter
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public String getJavaparameter() {
        return javaparameter;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.javaParameter
     *
     * @param javaparameter the value for mobileinfo.javaParameter
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setJavaparameter(String javaparameter) {
        this.javaparameter = javaparameter;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.reserve1
     *
     * @return the value of mobileinfo.reserve1
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.reserve1
     *
     * @param reserve1 the value for mobileinfo.reserve1
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.reserve2
     *
     * @return the value of mobileinfo.reserve2
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.reserve2
     *
     * @param reserve2 the value for mobileinfo.reserve2
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.mtime
     *
     * @return the value of mobileinfo.mtime
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.mtime
     *
     * @param mtime the value for mobileinfo.mtime
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column mobileinfo.remark
     *
     * @return the value of mobileinfo.remark
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column mobileinfo.remark
     *
     * @param remark the value for mobileinfo.remark
     *
     * @abatorgenerated Wed Jul 28 14:13:04 CST 2010
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
    
    private String pageName;


	public String getPageName() {
		return pageName;
	}

	public void setPageName(String pageName) {
		this.pageName = pageName;
	}
}