package com.tcl.portal.domain;

public class Types {
    public static final String CACHE_TYPES = "typeCache";

	/**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column types.id
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column types.fid
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    private Integer fid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column types.typeValue
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    private String typevalue;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column types.allowance
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    private String allowance;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column types.id
     *
     * @return the value of types.id
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column types.id
     *
     * @param id the value for types.id
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column types.fid
     *
     * @return the value of types.fid
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column types.fid
     *
     * @param fid the value for types.fid
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column types.typeValue
     *
     * @return the value of types.typeValue
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    public String getTypevalue() {
        return typevalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column types.typeValue
     *
     * @param typevalue the value for types.typeValue
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    public void setTypevalue(String typevalue) {
        this.typevalue = typevalue;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column types.allowance
     *
     * @return the value of types.allowance
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    public String getAllowance() {
        return allowance;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column types.allowance
     *
     * @param allowance the value for types.allowance
     *
     * @abatorgenerated Wed Aug 25 16:09:45 CST 2010
     */
    public void setAllowance(String allowance) {
        this.allowance = allowance;
    }
}