package com.tcl.portal.form;

import java.util.Date;

public class ApprovalForm extends BaseForm{
	
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.id
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private Integer id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.game
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private String game;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.content
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private String content;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.proposer
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private Integer proposer;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.proTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private Date protime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.checker
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private Integer checker;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.checkInfo
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private String checkinfo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.checkTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private Date checktime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.finalChecker
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private Integer finalchecker;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.finalCheckInfo
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private String finalcheckinfo;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.finalCheckTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private Date finalchecktime;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to the database column approval.status
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	private Integer status;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.id
	 * @return  the value of approval.id
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.id
	 * @param id  the value for approval.id
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.game
	 * @return  the value of approval.game
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public String getGame() {
		return game;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.game
	 * @param game  the value for approval.game
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setGame(String game) {
		this.game = game;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.content
	 * @return  the value of approval.content
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.content
	 * @param content  the value for approval.content
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.proposer
	 * @return  the value of approval.proposer
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public Integer getProposer() {
		return proposer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.proposer
	 * @param proposer  the value for approval.proposer
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setProposer(Integer proposer) {
		this.proposer = proposer;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.proTime
	 * @return  the value of approval.proTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public Date getProtime() {
		return protime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.proTime
	 * @param protime  the value for approval.proTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setProtime(Date protime) {
		this.protime = protime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.checker
	 * @return  the value of approval.checker
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public Integer getChecker() {
		return checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.checker
	 * @param checker  the value for approval.checker
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setChecker(Integer checker) {
		this.checker = checker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.checkInfo
	 * @return  the value of approval.checkInfo
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public String getCheckinfo() {
		return checkinfo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.checkInfo
	 * @param checkinfo  the value for approval.checkInfo
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setCheckinfo(String checkinfo) {
		this.checkinfo = checkinfo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.checkTime
	 * @return  the value of approval.checkTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public Date getChecktime() {
		return checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.checkTime
	 * @param checktime  the value for approval.checkTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setChecktime(Date checktime) {
		this.checktime = checktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.finalChecker
	 * @return  the value of approval.finalChecker
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public Integer getFinalchecker() {
		return finalchecker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.finalChecker
	 * @param finalchecker  the value for approval.finalChecker
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setFinalchecker(Integer finalchecker) {
		this.finalchecker = finalchecker;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.finalCheckInfo
	 * @return  the value of approval.finalCheckInfo
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public String getFinalcheckinfo() {
		return finalcheckinfo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.finalCheckInfo
	 * @param finalcheckinfo  the value for approval.finalCheckInfo
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setFinalcheckinfo(String finalcheckinfo) {
		this.finalcheckinfo = finalcheckinfo;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.finalCheckTime
	 * @return  the value of approval.finalCheckTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public Date getFinalchecktime() {
		return finalchecktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.finalCheckTime
	 * @param finalchecktime  the value for approval.finalCheckTime
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setFinalchecktime(Date finalchecktime) {
		this.finalchecktime = finalchecktime;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the value of the database column approval.status
	 * @return  the value of approval.status
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the value of the database column approval.status
	 * @param status  the value for approval.status
	 * @abatorgenerated  Wed Jul 28 14:13:00 CST 2010
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}
	
	//申请人，审批人，终审人名字
	private String proposerName;
	
	private String checkerName;
	
	private String finalcheckerName;

	public String getProposerName() {
		return proposerName;
	}

	public void setProposerName(String proposerName) {
		this.proposerName = proposerName;
	}

	public String getCheckerName() {
		return checkerName;
	}

	public void setCheckerName(String checkerName) {
		this.checkerName = checkerName;
	}

	public String getFinalcheckerName() {
		return finalcheckerName;
	}

	public void setFinalcheckerName(String finalcheckerName) {
		this.finalcheckerName = finalcheckerName;
	}
}
