package com.tcl.portal.form;

public class LanguageForm extends BaseForm{
	
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column language.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column language.language
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private String language;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column language.remarker
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    private String remarker;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column language.id
     *
     * @return the value of language.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column language.id
     *
     * @param id the value for language.id
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column language.language
     *
     * @return the value of language.language
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column language.language
     *
     * @param language the value for language.language
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column language.remarker
     *
     * @return the value of language.remarker
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public String getRemarker() {
        return remarker;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column language.remarker
     *
     * @param remarker the value for language.remarker
     *
     * @abatorgenerated Wed Jul 28 14:13:03 CST 2010
     */
    public void setRemarker(String remarker) {
        this.remarker = remarker;
    }
}
