package com.tcl.portal.form;

public class UserForm extends BaseForm{
	
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.id
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.name
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.password
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    private String password;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.disabled
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    private Integer disabled;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column user.role_id
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    private Integer roleId;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.id
     *
     * @return the value of user.id
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.id
     *
     * @param id the value for user.id
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.name
     *
     * @return the value of user.name
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.name
     *
     * @param name the value for user.name
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.disabled
     *
     * @return the value of user.disabled
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public Integer getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.disabled
     *
     * @param disabled the value for user.disabled
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public void setDisabled(Integer disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column user.role_id
     *
     * @return the value of user.role_id
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column user.role_id
     *
     * @param roleId the value for user.role_id
     *
     * @abatorgenerated Tue May 18 10:36:01 CST 2010
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}
