package com.tcl.paypal.domain;

import java.util.Date;

public class Business {
    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.id
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.goodId
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    private Integer goodid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.buyName
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    private String buyname;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.buyTime
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    private Date buytime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.goodId
     *
     * @return the value of business.goodId
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    public Integer getGoodid() {
        return goodid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.goodId
     *
     * @param goodid the value for business.goodId
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    public void setGoodid(Integer goodid) {
        this.goodid = goodid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.buyName
     *
     * @return the value of business.buyName
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    public String getBuyname() {
        return buyname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.buyName
     *
     * @param buyname the value for business.buyName
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    public void setBuyname(String buyname) {
        this.buyname = buyname;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.buyTime
     *
     * @return the value of business.buyTime
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    public Date getBuytime() {
        return buytime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.buyTime
     *
     * @param buytime the value for business.buyTime
     *
     * @abatorgenerated Tue Sep 21 16:19:32 CST 2010
     */
    public void setBuytime(Date buytime) {
        this.buytime = buytime;
    }
}