package com.tclPaypal.form;

import java.util.Date;


public class BusinessForm extends BaseForm{
	
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.id
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.token
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    private String token;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.orderNum
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    private String ordernum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.customerPaypalNum
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    private String customerpaypalnum;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.profileId
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    private String profileid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.statute
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    private Integer statute;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column business.saveTime
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    private Date savetime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.id
     *
     * @return the value of business.id
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.id
     *
     * @param id the value for business.id
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.token
     *
     * @return the value of business.token
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.token
     *
     * @param token the value for business.token
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.orderNum
     *
     * @return the value of business.orderNum
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public String getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.orderNum
     *
     * @param ordernum the value for business.orderNum
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public void setOrdernum(String ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.customerPaypalNum
     *
     * @return the value of business.customerPaypalNum
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public String getCustomerpaypalnum() {
        return customerpaypalnum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.customerPaypalNum
     *
     * @param customerpaypalnum the value for business.customerPaypalNum
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public void setCustomerpaypalnum(String customerpaypalnum) {
        this.customerpaypalnum = customerpaypalnum;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.profileId
     *
     * @return the value of business.profileId
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public String getProfileid() {
        return profileid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.profileId
     *
     * @param profileid the value for business.profileId
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public void setProfileid(String profileid) {
        this.profileid = profileid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.statute
     *
     * @return the value of business.statute
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public Integer getStatute() {
        return statute;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.statute
     *
     * @param statute the value for business.statute
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public void setStatute(Integer statute) {
        this.statute = statute;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column business.saveTime
     *
     * @return the value of business.saveTime
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public Date getSavetime() {
        return savetime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column business.saveTime
     *
     * @param savetime the value for business.saveTime
     *
     * @abatorgenerated Wed Dec 22 10:33:54 CST 2010
     */
    public void setSavetime(Date savetime) {
        this.savetime = savetime;
    }
}
