package com.tcl.portal.form;

import java.util.Date;

public class ChangelogForm extends BaseForm{
	
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column changelog.id
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column changelog.gameResourceId
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private Integer gameresourceid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column changelog.price
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private Long price;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column changelog.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private Integer disable;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column changelog.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    private Date ctime;

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column changelog.id
     *
     * @return the value of changelog.id
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column changelog.id
     *
     * @param id the value for changelog.id
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column changelog.gameResourceId
     *
     * @return the value of changelog.gameResourceId
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public Integer getGameresourceid() {
        return gameresourceid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column changelog.gameResourceId
     *
     * @param gameresourceid the value for changelog.gameResourceId
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setGameresourceid(Integer gameresourceid) {
        this.gameresourceid = gameresourceid;
    }

 
    public Integer getDisable() {
        return disable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column changelog.disable
     *
     * @param disable the value for changelog.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setDisable(Integer disable) {
        this.disable = disable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column changelog.ctime
     *
     * @return the value of changelog.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column changelog.ctime
     *
     * @param ctime the value for changelog.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:00 CST 2010
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

	public Long getPrice() {
		return price;
	}

	public void setPrice(Long price) {
		this.price = price;
	}
}
