package com.tcl.portal.form;

import java.util.Date;

public class CommentForm extends BaseForm{
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column comment.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column comment.mobileUserId
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Integer mobileuserid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column comment.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Integer gameid;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column comment.content
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private String content;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column comment.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Date ctime;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column comment.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    private Integer disable;
    
    private String did;
    
    
    public String getDid() {
		return did;
	}

	public void setDid(String did) {
		this.did = did;
	}

	/**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column comment.id
     *
     * @return the value of comment.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column comment.id
     *
     * @param id the value for comment.id
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column comment.mobileUserId
     *
     * @return the value of comment.mobileUserId
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Integer getMobileuserid() {
        return mobileuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column comment.mobileUserId
     *
     * @param mobileuserid the value for comment.mobileUserId
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setMobileuserid(Integer mobileuserid) {
        this.mobileuserid = mobileuserid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column comment.gameId
     *
     * @return the value of comment.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Integer getGameid() {
        return gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column comment.gameId
     *
     * @param gameid the value for comment.gameId
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setGameid(Integer gameid) {
        this.gameid = gameid;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column comment.content
     *
     * @return the value of comment.content
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column comment.content
     *
     * @param content the value for comment.content
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column comment.ctime
     *
     * @return the value of comment.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Date getCtime() {
        return ctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column comment.ctime
     *
     * @param ctime the value for comment.ctime
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setCtime(Date ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column comment.disable
     *
     * @return the value of comment.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public Integer getDisable() {
        return disable;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column comment.disable
     *
     * @param disable the value for comment.disable
     *
     * @abatorgenerated Wed Jul 28 14:13:01 CST 2010
     */
    public void setDisable(Integer disable) {
        this.disable = disable;
    }
}
