package com.tcl.portal.form;

public class SystemparameterForm extends BaseForm{
	
	 /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column systemparameter.id
     *
     * @abatorgenerated Mon Sep 13 09:31:14 CST 2010
     */
    private Integer id;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column systemparameter.name
     *
     * @abatorgenerated Mon Sep 13 09:31:14 CST 2010
     */
    private String name;

    /**
     * This field was generated by Abator for iBATIS.
     * This field corresponds to the database column systemparameter.value
     *
     * @abatorgenerated Mon Sep 13 09:31:14 CST 2010
     */
    private String value;

    private String remarker;
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column systemparameter.id
     *
     * @param id the value for systemparameter.id
     *
     * @abatorgenerated Mon Sep 13 09:31:14 CST 2010
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column systemparameter.name
     *
     * @return the value of systemparameter.name
     *
     * @abatorgenerated Mon Sep 13 09:31:14 CST 2010
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column systemparameter.name
     *
     * @param name the value for systemparameter.name
     *
     * @abatorgenerated Mon Sep 13 09:31:14 CST 2010
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method returns the value of the database column systemparameter.value
     *
     * @return the value of systemparameter.value
     *
     * @abatorgenerated Mon Sep 13 09:31:14 CST 2010
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by Abator for iBATIS.
     * This method sets the value of the database column systemparameter.value
     *
     * @param value the value for systemparameter.value
     *
     * @abatorgenerated Mon Sep 13 09:31:14 CST 2010
     */
    public void setValue(String value) {
        this.value = value;
    }

	public String getRemarker() {
		return remarker;
	}

	public void setRemarker(String remarker) {
		this.remarker = remarker;
	}
    
}
